services:
  db:
    image: postgres:15
    container_name: poc-client
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: poc
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/poc/data
volumes:
  db_data: